variable "VPC-NAME" {}
variable "VPC-CIDR" {}
variable "IGW-NAME" {}
variable "PUBLIC-CIDR1" {}
variable "PUBLIC-SUBNET1" {}
variable "PRIVATE-CIDR1" {}
variable "PRIVATE-SUBNET1" {}
variable "EIP-NAME1" {}
variable "NGW-NAME1" {}
variable "PUBLIC-RT-NAME1" {}
variable "PRIVATE-RT-NAME1" {}