version: '3'
services:
  dev-web:
    container_name: web
    image: dockerregistry.ecosmob.net:5000/masergy-web-dev:v97
      restart: alwyas
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./host/directory:/container/directory
      
  dev-db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    volumes:
      - ./host/directory:/container/directory
